os: osx
language: swift
osx_image: xcode9.4

if: tag =~ /^[0-9]+\.[0-9]+\.[0-9]+/

stages:
  - swiftpm
  - carthage

jobs:
  include:
    - &swiftpm
      stage: swiftpm
      osx_image: xcode9.4
      script: swift build
    - <<: *swiftpm
      osx_image: xcode10.3
    - <<: *swiftpm
      osx_image: xcode11.6

    - &carthage
      stage: carthage
      osx_image: xcode9.4
      install: sed -i '' "s/SWIFT_TREAT_WARNINGS_AS_ERRORS = NO;/SWIFT_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
      script: carthage build --no-skip-current
    - <<: *carthage
      osx_image: xcode10.3
    - <<: *carthage
      osx_image: xcode11.6
