[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
path = "JSTColorPicker"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "JSTColorPicker"
localizablePath = "JSTColorPicker"
defaultToKeys = false
additive = false
unstripped = false

[update.transform]
codePath = "JSTColorPicker"
localizablePath = "JSTColorPicker"
transformer = "foundation"
supportedLanguageEnumPath = "JSTColorPicker"
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "JSTColorPicker"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "JSTColorPicker"
duplicateKeys = true
emptyValues = true
